#!/usr/bin/env php
<?php

require __DIR__.'/app/bootstrap.php';

use Rancherize\Blueprint\Validation\Exceptions\ValidationFailedException;
use Rancherize\Configuration\Services\ProjectConfiguration;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\ConsoleEvents;
use Symfony\Component\Console\Event\ConsoleCommandEvent;
use Symfony\Component\EventDispatcher\EventDispatcher;

/**
 * @var EventDispatcher $dispatcher
 */
$dispatcher = container('event');
$application = new Application('rancherize');
$application->setDispatcher($dispatcher);
$c = container();
// register application in container
$c['app'] = function () use ($application) { return $application; };

$dispatcher->addListener(\Symfony\Component\Console\ConsoleEvents::EXCEPTION, function(\Symfony\Component\Console\Event\ConsoleExceptionEvent $event) {

	$e = $event->getException();
	$output = $event->getOutput();


	if ( $e instanceof ValidationFailedException ) {

		$formatter = $output->getFormatter();

		$headline = ' Validation failed ';
		$output->writeln( [
			'',
			' ' . $formatter->format( sprintf( "<error> %s </error>", str_repeat(' ', strlen($headline)) ) ) . ' ',
			$formatter->format(" <error> $headline </error>"),
			' ' . $formatter->format( sprintf( "<error> %s </error>", str_repeat('=', strlen($headline)) ) ) . ' ',
			' ' . $formatter->format( sprintf( "<error> %s </error>", str_repeat(' ', strlen($headline)) ) ) . ' ',
			"",
		]);

		/**
		 * @var \Rancherize\Services\ValidateService $validateService
		 */
		$validateService = container('validate-service');
		$validateService->print($e, $output);
	}

});

$dispatcher->addListener(ConsoleEvents::COMMAND, function (ConsoleCommandEvent $event) {
    // get the input instance
    $input = $event->getInput();

    // get the output instance
    $output = $event->getOutput();

    // get the command to be executed
    $command = $event->getCommand();

    // get the application
    $application = $command->getApplication();

    $c = container();
    $c['output'] = function() use ($output) { return $output; };
	$c['input'] = function() use ($input) { return $input; };
	$c['application'] = function() use ($application) { return $application; };
	$c['command'] = function() use ($command) { return $command; };
	$c['process-helper'] = function() use ($command) { return $command->getHelper('process'); };
});

// ... register commands
$commands = require_once __DIR__.'/app/lists/commands.php';
foreach($commands as $commandName) {
    $command = new $commandName;
    $application->add($command);
}

$internalPlugins = require_once __DIR__.'/app/lists/plugins.php';
foreach($internalPlugins as $internalPlugin) {
	/**
	 * @var \Rancherize\Plugin\Loader\ExtraPluginLoaderDecorator $pluginLoaderExtra
	 */
    $pluginLoaderExtra = container('plugin-loader-extra');
    $pluginLoaderExtra->registerExtra($internalPlugin);
}

try {

		/**
	 * @var ProjectConfiguration $projectConfig
	 */
	$projectConfig = container('project-config-service');

	/**
	 * @var \Rancherize\Configuration\Configurable $configuration
	 */
	$configuration = container('configuration');
	$configuration = $projectConfig->load($configuration);
	container()->offsetSet('project-config', $configuration);

	/**
	 * @var \Rancherize\Plugin\Loader\PluginLoader $pluginLoader
	 */
	$pluginLoader = container('plugin-loader');
	$pluginLoader->load( $configuration, $application, container() );

} catch(Exception $e) {

    echo "Warning! Load Plugins failed: ". $e->getMessage()."\n";

}


$returnCode = $application->run();


return $returnCode;
